export enum UserRole {
  CITIZEN = 'CITIZEN',
  UNIVERSITY_ADMIN = 'UNIVERSITY_ADMIN',
  FACULTY = 'FACULTY',
  STUDENT = 'STUDENT',
  INDUSTRY_ADMIN = 'INDUSTRY_ADMIN',
  INDUSTRY_MEMBER = 'INDUSTRY_MEMBER',
  GOVERNMENT_ADMIN = 'GOVERNMENT_ADMIN',
  GOVERNMENT_OFFICER = 'GOVERNMENT_OFFICER',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  // Backward-compatibility aliases
  INDUSTRY = 'INDUSTRY',
  GOVERNMENT = 'GOVERNMENT',
}

export enum JurisdictionScope {
  DISTRICT = 'DISTRICT',
  STATE = 'STATE',
  NATIONAL = 'NATIONAL',
}

export enum OrganizationRole {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum MembershipStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  REVOKED = 'REVOKED',
}

export enum ClaimRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum OrganizationType {
  INSTITUTION = 'INSTITUTION',
  INDUSTRY = 'INDUSTRY',
  GOVERNMENT = 'GOVERNMENT',
  NGO = 'NGO',
  COMMUNITY_ORGANIZATION = 'COMMUNITY_ORGANIZATION',
  OTHER = 'OTHER',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum CapabilitySource {
  OFFICIAL_WEBSITE = 'OFFICIAL_WEBSITE',
  PUBLIC_DATA = 'PUBLIC_DATA',
  ORGANIZATION_PROVIDED = 'ORGANIZATION_PROVIDED',
  ADMIN_ENTERED = 'ADMIN_ENTERED',
  PROJECT_HISTORY = 'PROJECT_HISTORY',
  PARTNER_VERIFIED = 'PARTNER_VERIFIED',
}

export enum ChallengeStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VALIDATED = 'VALIDATED',
  REJECTED = 'REJECTED',
  MATCHING = 'MATCHING',
  MATCHED = 'MATCHED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
  PROJECT_INITIATED = 'PROJECT_INITIATED',
}

export enum CitizenSeverity {
  NOT_SURE = 'NOT_SURE',
  MODERATE = 'MODERATE',
  SERIOUS = 'SERIOUS',
}

export enum ChallengePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EvidenceType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  AUDIO = 'AUDIO',
  LINK = 'LINK',
  LOCATION_DATA = 'LOCATION_DATA',
  SURVEY_DATA = 'SURVEY_DATA',
  OTHER = 'OTHER',
}

export enum ProjectStatus {
  PROPOSED = 'PROPOSED', // Phase 6 formation initial state (treated as INITIATED)
  INITIATED = 'INITIATED',
  PLANNING = 'PLANNING',
  KICKOFF_PENDING = 'KICKOFF_PENDING',
  KICKOFF_REVISION = 'KICKOFF_REVISION',
  ACTIVE = 'ACTIVE',
  PROTOTYPE_DEVELOPMENT = 'PROTOTYPE_DEVELOPMENT',
  TESTING = 'TESTING',
  PILOT = 'PILOT',
  DEPLOYMENT = 'DEPLOYMENT',
  BLOCKED = 'BLOCKED',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  IMPACT_VERIFIED = 'IMPACT_VERIFIED',
  TERMINATED = 'TERMINATED',
  // Backward-compatibility aliases
  APPROVED = 'APPROVED',
  IN_DEVELOPMENT = 'IN_DEVELOPMENT',
  PILOT_DEPLOYMENT = 'PILOT_DEPLOYMENT',
  VERIFIED = 'VERIFIED',
  CANCELLED = 'CANCELLED',
}

export enum ParticipantRole {
  LEAD = 'LEAD',
  PARTNER = 'PARTNER',
  SUPPORT = 'SUPPORT',
  FUNDER = 'FUNDER',
  // Backward-compatibility aliases
  LEAD_INSTITUTION = 'LEAD_INSTITUTION',
  INDUSTRY_PARTNER = 'INDUSTRY_PARTNER',
  CONSORTIUM_PARTNER = 'CONSORTIUM_PARTNER',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  REVIEW_REQUESTED = 'REVIEW_REQUESTED',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  APPROVED = 'APPROVED',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}

export enum DeliverableDocumentType {
  REPORT = 'REPORT',
  PROTOTYPE_SPEC = 'PROTOTYPE_SPEC',
  PROTOTYPE = 'PROTOTYPE',
  FIELD_PHOTO = 'FIELD_PHOTO',
  CERTIFICATION = 'CERTIFICATION',
  TECHNICAL_REPORT = 'TECHNICAL_REPORT',
  TESTING_REPORT = 'TESTING_REPORT',
  PILOT_REPORT = 'PILOT_REPORT',
  DEPLOYMENT_DOCS = 'DEPLOYMENT_DOCS',
  TRAINING_MATERIAL = 'TRAINING_MATERIAL',
  FINAL_REPORT = 'FINAL_REPORT',
  EVIDENCE = 'EVIDENCE',
  OTHER = 'OTHER',
}

export enum ProjectUpdateType {
  PROGRESS = 'PROGRESS',
  BLOCKER = 'BLOCKER',
  RESOLUTION = 'RESOLUTION',
}

export enum ProjectReviewAction {
  KICKOFF_APPROVED = 'KICKOFF_APPROVED',
  KICKOFF_REVISION_REQUIRED = 'KICKOFF_REVISION_REQUIRED',
  MILESTONE_APPROVED = 'MILESTONE_APPROVED',
  MILESTONE_REVISION_REQUIRED = 'MILESTONE_REVISION_REQUIRED',
  STAGE_APPROVED = 'STAGE_APPROVED',
  BLOCKER_REVIEWED = 'BLOCKER_REVIEWED',
  BLOCKER_RESOLVED = 'BLOCKER_RESOLVED',
  PROJECT_COMPLETED = 'PROJECT_COMPLETED',
  PROJECT_TERMINATED = 'PROJECT_TERMINATED',
  IMPACT_VERIFIED = 'IMPACT_VERIFIED',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  MODIFIED = 'MODIFIED',
}

export enum IndustrySupportCode {
  FUNDING = 'FUNDING',
  MENTORSHIP = 'MENTORSHIP',
  HARDWARE = 'HARDWARE',
  SOFTWARE = 'SOFTWARE',
  PROTOTYPING = 'PROTOTYPING',
  TESTING = 'TESTING',
  MANUFACTURING = 'MANUFACTURING',
  PILOT_DEPLOYMENT = 'PILOT_DEPLOYMENT',
  MARKET_ACCESS = 'MARKET_ACCESS',
  TECHNOLOGY_TRANSFER = 'TECHNOLOGY_TRANSFER',
}

export enum IndexingStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
}

export enum GeographicReach {
  DISTRICT = 'DISTRICT',
  STATEWIDE = 'STATEWIDE',
  NATIONAL = 'NATIONAL',
}

export enum EoiStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DISCUSSION_REQUIRED = 'DISCUSSION_REQUIRED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  PROJECT_FORMED = 'PROJECT_FORMED',
}

export enum EoiTimeline {
  LESS_THAN_3_MONTHS = 'LESS_THAN_3_MONTHS',
  THREE_TO_SIX_MONTHS = 'THREE_TO_SIX_MONTHS',
  SIX_TO_TWELVE_MONTHS = 'SIX_TO_TWELVE_MONTHS',
  MORE_THAN_12_MONTHS = 'MORE_THAN_12_MONTHS',
}

export enum EoiContributionType {
  RESEARCH = 'RESEARCH',
  EXPERTISE = 'EXPERTISE',
  FACULTY = 'FACULTY',
  STUDENT_TEAM = 'STUDENT_TEAM',
  TECHNOLOGY = 'TECHNOLOGY',
  PROTOTYPING = 'PROTOTYPING',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  TESTING = 'TESTING',
  MENTORSHIP = 'MENTORSHIP',
  FIELD_IMPLEMENTATION = 'FIELD_IMPLEMENTATION',
  MANUFACTURING = 'MANUFACTURING',
  DEPLOYMENT = 'DEPLOYMENT',
  CSR_SUPPORT = 'CSR_SUPPORT',
  FUNDING_SUPPORT = 'FUNDING_SUPPORT',
  OTHER = 'OTHER',
}

export enum EoiEvidenceType {
  TECHNICAL_PROPOSAL = 'TECHNICAL_PROPOSAL',
  COST_ESTIMATE = 'COST_ESTIMATE',
  PROTOTYPE_SPECIFICATION = 'PROTOTYPE_SPECIFICATION',
  IMPLEMENTATION_CONCEPT = 'IMPLEMENTATION_CONCEPT',
  SUPPORTING_LETTER = 'SUPPORTING_LETTER',
  OTHER = 'OTHER',
}

export enum EoiReviewAction {
  SUBMIT = 'SUBMIT',
  REQUEST_DISCUSSION = 'REQUEST_DISCUSSION',
  RESUBMIT = 'RESUBMIT',
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  WITHDRAW = 'WITHDRAW',
}

export enum ProposedSolutionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PUBLISHED = 'PUBLISHED',
  COLLABORATION_OPEN = 'COLLABORATION_OPEN',
  CONVERTED_TO_PROJECT = 'CONVERTED_TO_PROJECT',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED',
}

export enum SolutionVisibility {
  PUBLIC = 'PUBLIC',
  INTERNAL = 'INTERNAL',
  CONSORTIUM = 'CONSORTIUM',
}

export enum SolutionCollaborationType {
  FUNDING = 'FUNDING',
  MENTORSHIP = 'MENTORSHIP',
  TECHNOLOGY = 'TECHNOLOGY',
  SOFTWARE = 'SOFTWARE',
  HARDWARE = 'HARDWARE',
  PROTOTYPING = 'PROTOTYPING',
  TESTING = 'TESTING',
  MANUFACTURING = 'MANUFACTURING',
  PILOT_SUPPORT = 'PILOT_SUPPORT',
  DEPLOYMENT_SUPPORT = 'DEPLOYMENT_SUPPORT',
  TECHNOLOGY_TRANSFER = 'TECHNOLOGY_TRANSFER',
  RESEARCH_COLLABORATION = 'RESEARCH_COLLABORATION',
  TECHNICAL_EXPERTISE = 'TECHNICAL_EXPERTISE',
  CSR_SUPPORT = 'CSR_SUPPORT',
  OTHER = 'OTHER',
}

export enum SolutionCollaborationStatus {
  OFFERED = 'OFFERED',
  UNDER_DISCUSSION = 'UNDER_DISCUSSION',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  CONVERTED_TO_PROJECT = 'CONVERTED_TO_PROJECT',
}

export enum SolutionTeamRole {
  PROJECT_LEAD = 'PROJECT_LEAD',
  FACULTY_MENTOR = 'FACULTY_MENTOR',
  STUDENT_RESEARCHER = 'STUDENT_RESEARCHER',
  CO_INVESTIGATOR = 'CO_INVESTIGATOR',
  ACADEMIC_COORDINATOR = 'ACADEMIC_COORDINATOR',
}

export enum SolutionDocumentType {
  TECHNICAL_PROPOSAL = 'TECHNICAL_PROPOSAL',
  COST_ESTIMATE = 'COST_ESTIMATE',
  PROTOTYPE_SPECIFICATION = 'PROTOTYPE_SPECIFICATION',
  BLUEPRINT = 'BLUEPRINT',
  SUPPORTING_LETTER = 'SUPPORTING_LETTER',
  OTHER = 'OTHER',
}

export enum ImpactAssessmentStatus {
  IMPACT_VERIFICATION_PENDING = 'IMPACT_VERIFICATION_PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ImpactMetricCategory {
  POPULATION_REACHED = 'POPULATION_REACHED',
  FINANCIAL_SAVINGS = 'FINANCIAL_SAVINGS',
  ENVIRONMENTAL_IMPACT = 'ENVIRONMENTAL_IMPACT',
  INFRASTRUCTURE_CREATED = 'INFRASTRUCTURE_CREATED',
  HEALTH_OUTCOMES = 'HEALTH_OUTCOMES',
  EFFICIENCY_IMPROVEMENT = 'EFFICIENCY_IMPROVEMENT',
}

export enum ImpactEvidenceType {
  FIELD_PHOTO = 'FIELD_PHOTO',
  BENEFICIARY_TESTIMONIAL = 'BENEFICIARY_TESTIMONIAL',
  GOVERNMENT_RECORD = 'GOVERNMENT_RECORD',
  IMPACT_REPORT = 'IMPACT_REPORT',
  MEASUREMENT_DATA = 'MEASUREMENT_DATA',
  CERTIFICATION = 'CERTIFICATION',
  OTHER = 'OTHER',
}

export enum ImpactReviewDecision {
  APPROVED = 'APPROVED',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  REJECTED = 'REJECTED',
  REVOKED = 'REVOKED',
}

export enum AcademicMemberRole {
  STUDENT = 'STUDENT',
  FACULTY_MENTOR = 'FACULTY_MENTOR',
  ACADEMIC_COORDINATOR = 'ACADEMIC_COORDINATOR',
}

export enum AcademicMemberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum ProjectContributionType {
  MENTORSHIP = 'MENTORSHIP',
  FUNDING = 'FUNDING',
  TECHNOLOGY = 'TECHNOLOGY',
  PROTOTYPING = 'PROTOTYPING',
  TESTING = 'TESTING',
  PILOT_SUPPORT = 'PILOT_SUPPORT',
  TECHNOLOGY_TRANSFER = 'TECHNOLOGY_TRANSFER',
  DEPLOYMENT_SUPPORT = 'DEPLOYMENT_SUPPORT',
}

export enum ContributionStatus {
  PROPOSED = 'PROPOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  CLARIFICATION_REQUESTED = 'CLARIFICATION_REQUESTED',
}

export enum ContributionVisibility {
  CONSORTIUM = 'CONSORTIUM',
  CONTRIBUTOR_AND_LEAD_ONLY = 'CONTRIBUTOR_AND_LEAD_ONLY',
}

export enum NotificationType {
  CHALLENGE_STATUS = 'CHALLENGE_STATUS',
  EOI_UPDATE = 'EOI_UPDATE',
  SOLUTION_UPDATE = 'SOLUTION_UPDATE',
  COLLABORATION_UPDATE = 'COLLABORATION_UPDATE',
  PROJECT_GOVERNANCE = 'PROJECT_GOVERNANCE',
  MILESTONE_ACTION = 'MILESTONE_ACTION',
  CONTRIBUTION_UPDATE = 'CONTRIBUTION_UPDATE',
  IMPACT_UPDATE = 'IMPACT_UPDATE',
  SYSTEM = 'SYSTEM',
  INSTITUTION_VERIFICATION = 'INSTITUTION_VERIFICATION',
}

export enum InnovationOutcomeType {
  PATENT = 'PATENT',
  PATENT_APPLICATION = 'PATENT_APPLICATION',
  IP_GENERATED = 'IP_GENERATED',
  STARTUP_CREATED = 'STARTUP_CREATED',
  INNOVATION_OUTCOME = 'INNOVATION_OUTCOME',
  TECHNOLOGY_TRANSFER = 'TECHNOLOGY_TRANSFER',
}

export enum InnovationOutcomeStatus {
  PROPOSED = 'PROPOSED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ProjectIpAssessmentStatus {
  NO_IP_IDENTIFIED = 'NO_IP_IDENTIFIED',
  IP_ASSESSMENT_PENDING = 'IP_ASSESSMENT_PENDING',
  POTENTIAL_IP_IDENTIFIED = 'POTENTIAL_IP_IDENTIFIED',
  PATENT_APPLICATION_FILED = 'PATENT_APPLICATION_FILED',
  PATENT_GRANTED = 'PATENT_GRANTED',
  OTHER_PROTECTION = 'OTHER_PROTECTION',
  CONFIDENTIAL = 'CONFIDENTIAL',
}

export enum ProblemClusterStatus {
  AWAITING_GOVERNMENT_VERIFICATION = 'AWAITING_GOVERNMENT_VERIFICATION',
  VALIDATED = 'VALIDATED',
  OPEN_FOR_SOLUTIONS = 'OPEN_FOR_SOLUTIONS',
  COLLABORATION = 'COLLABORATION',
  PROJECT_INITIATED = 'PROJECT_INITIATED',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum ClusteringStatus {
  CLUSTERED = 'CLUSTERED',
  POTENTIAL_MATCH = 'POTENTIAL_MATCH',
  INDEPENDENT = 'INDEPENDENT',
}

export enum InstitutionType {
  PRI = 'PRI',
  ULB = 'ULB',
  GOVERNMENT_DEPARTMENT = 'GOVERNMENT_DEPARTMENT',
}

export enum InstitutionSubtype {
  GRAM_PANCHAYAT = 'GRAM_PANCHAYAT',
  PANCHAYAT_SAMITI = 'PANCHAYAT_SAMITI',
  ZILLA_PARISHAD = 'ZILLA_PARISHAD',
  MUNICIPAL_CORPORATION = 'MUNICIPAL_CORPORATION',
  MUNICIPAL_COUNCIL = 'MUNICIPAL_COUNCIL',
  NAGAR_PANCHAYAT = 'NAGAR_PANCHAYAT',
  STATE_DEPARTMENT = 'STATE_DEPARTMENT',
  DISTRICT_OFFICE = 'DISTRICT_OFFICE',
  BLOCK_OFFICE = 'BLOCK_OFFICE',
}

export enum InstitutionStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum RepresentativeRelationship {
  EMPLOYEE = 'EMPLOYEE',
  ELECTED_REPRESENTATIVE = 'ELECTED_REPRESENTATIVE',
  AUTHORIZED_OFFICER = 'AUTHORIZED_OFFICER',
  AUTHORIZED_STAFF = 'AUTHORIZED_STAFF',
}

export enum AuthorityVerificationStatus {
  PENDING = 'PENDING',
  IDENTITY_VERIFIED = 'IDENTITY_VERIFIED',
  AFFILIATION_PENDING = 'AFFILIATION_PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  LEGACY_PENDING_REVIEW = 'LEGACY_PENDING_REVIEW',
}

export enum AuthorityVerificationSource {
  OFFICIAL_GOVERNMENT_RECORD = 'OFFICIAL_GOVERNMENT_RECORD',
  GOVERNMENT_SSO = 'GOVERNMENT_SSO',
  OFFICIAL_APPOINTMENT_RECORD = 'OFFICIAL_APPOINTMENT_RECORD',
  AUTHORIZED_DOCUMENT_REVIEW = 'AUTHORIZED_DOCUMENT_REVIEW',
  AUTHORIZED_ADMIN_REVIEW = 'AUTHORIZED_ADMIN_REVIEW',
  FUTURE_GOVERNMENT_API = 'FUTURE_GOVERNMENT_API',
}

export enum InstitutionEvidenceType {
  APPOINTMENT_LETTER = 'APPOINTMENT_LETTER',
  OFFICIAL_ID_CARD = 'OFFICIAL_ID_CARD',
  AUTHORIZATION_RESOLUTION = 'AUTHORIZATION_RESOLUTION',
  GOVERNMENT_ORDER = 'GOVERNMENT_ORDER',
  OTHER = 'OTHER',
}

export enum ReporterType {
  INDIVIDUAL = 'INDIVIDUAL',
  COMMUNITY = 'COMMUNITY',
  PRI = 'PRI',
  ULB = 'ULB',
  GOVERNMENT_DEPARTMENT = 'GOVERNMENT_DEPARTMENT',
}

